apiVersion : apps/v1
kind: Deployment
metadata:
  name: cwp-poc-app 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cwp-poc-app
  template:
    metadata:
      labels:
        app: cwp-poc-app 
    spec:
      containers:
        - name: cwp-poc-app 
          image: cwppoccontainerregistry.azurecr.io/cwp-poc-app
          ports:
          - containerPort: 80
